apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: difyai
  labels:
    app: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx
        image: 'docker.m.daocloud.io/library/nginx:latest'
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: difyai-config
        ports:
          - containerPort: 80
          - containerPort: 443
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf.template
            name: nginx-configmap-0
            subPath: nginx.conf.template
          - mountPath: /etc/nginx/proxy.conf.template
            name: nginx-configmap-1
            subPath: proxy.conf.template
          - mountPath: /etc/nginx/https.conf.template
            name: nginx-configmap-2
            subPath: https.conf.template
          - mountPath: /etc/nginx/conf.d/default.conf.template
            subPath: default.conf.template
            name: nginx-configmap-3
          - mountPath: /docker-entrypoint-mount.sh
            name: nginx-configmap-4
            subPath: docker-entrypoint-mount.sh
          - mountPath: /etc/ssl
            name: nginx-configmap-5
        command: [ "sh","-c","cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/\r$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh" ]
      volumes:
        - configMap:
            items:
              - key: nginx.conf.template
                path: nginx.conf.template
            name: nginx-configmap-0
          name: nginx-configmap-0
        - configMap:
            items:
              - key: proxy.conf.template
                path: proxy.conf.template
            name: nginx-configmap-1
          name: nginx-configmap-1
        - configMap:
            items:
              - key: https.conf.template
                path: https.conf.template
            name: nginx-configmap-2
          name: nginx-configmap-2
        - configMap:
            items:
              - key: default.conf.template
                path: default.conf.template
            name: nginx-configmap-3
          name: nginx-configmap-3
        - configMap:
            items:
              - key: docker-entrypoint.sh
                path: docker-entrypoint-mount.sh
            name: nginx-configmap-4
          name: nginx-configmap-4
        - configMap:
            name: nginx-configmap-5
          name: nginx-configmap-5